#pragma once

// Win32 virtual keycodes. 
#define SEACREST_MOUSE_LBUTTON			1
#define SEACREST_MOUSE_RBUTTON			2
#define SEACREST_MOUSE_CANCEL			3
#define SEACREST_MOUSE_MBUTTON			4
#define SEACREST_MOUSE_XBUTTON1			5
#define SEACREST_MOUSE_XBUTTON2			6
